spring:
  application:
    name: shopping-mall
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shopping_mall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        jdbc:
        time_zone: Asia/Seoul
    open-in-view: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ${BATCH_SCHEMA_INITIALIZE:never}

server:
  port: ${SERVER_PORT:8080}
