spring:
  config:
    import: ${AWS_SECRETS_MANAGER_IMPORT:aws-secretsmanager:/shopping-mall/aws}
  cloud:
    aws:
      secretsmanager:
        enabled: true
        region: ${AWS_REGION:ap-northeast-2}
